name: Bug Report
description: Report a reproducible problem with the script
labels: [bug]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide exact commands and behavior
  - type: input
    attributes:
      label: OS and version
  - type: input
    attributes:
      label: Shell and version
  - type: input
    attributes:
      label: Script version (or commit hash)
