name: Feature Request
description: Suggest an improvement or new feature
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What would you like to see?
      description: Describe your idea or suggestion
  - type: textarea
    attributes:
      label: Why is this useful?
      description: Explain why this is a meaningful addition
